FROM node:22-alpine AS deps
WORKDIR /app
COPY package*.json ./
RUN npm ci

FROM node:22-alpine AS builder
WORKDIR /app
ENV NEXT_TELEMETRY_DISABLED=1
ARG NEXT_PUBLIC_BASE_URL
ARG NEXT_PUBLIC_MEDUSA_BACKEND_URL
ARG NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY
ARG NEXT_PUBLIC_MEDUSA_SALES_CHANNEL_ID
ARG NEXT_PUBLIC_STRIPE_KEY
ARG NEXT_PUBLIC_TURNSTILE_SITE_KEY
ARG NEXT_PUBLIC_SUPPORT_EMAIL
ARG NEXT_PUBLIC_COMPANY_LEGAL_NAME
ARG NEXT_PUBLIC_COMPANY_REG_NO
ARG NEXT_PUBLIC_COMPANY_ADDRESS
ARG NEXT_PUBLIC_SOCIAL_LINKS
ARG NEXT_PUBLIC_IMAGE_DOMAINS
ARG STRAPI_API_URL
ARG STRAPI_API_TOKEN
ENV NEXT_PUBLIC_BASE_URL=$NEXT_PUBLIC_BASE_URL
ENV NEXT_PUBLIC_MEDUSA_BACKEND_URL=$NEXT_PUBLIC_MEDUSA_BACKEND_URL
ENV NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY=$NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY
ENV NEXT_PUBLIC_MEDUSA_SALES_CHANNEL_ID=$NEXT_PUBLIC_MEDUSA_SALES_CHANNEL_ID
ENV NEXT_PUBLIC_STRIPE_KEY=$NEXT_PUBLIC_STRIPE_KEY
ENV NEXT_PUBLIC_TURNSTILE_SITE_KEY=$NEXT_PUBLIC_TURNSTILE_SITE_KEY
ENV NEXT_PUBLIC_SUPPORT_EMAIL=$NEXT_PUBLIC_SUPPORT_EMAIL
ENV NEXT_PUBLIC_COMPANY_LEGAL_NAME=$NEXT_PUBLIC_COMPANY_LEGAL_NAME
ENV NEXT_PUBLIC_COMPANY_REG_NO=$NEXT_PUBLIC_COMPANY_REG_NO
ENV NEXT_PUBLIC_COMPANY_ADDRESS=$NEXT_PUBLIC_COMPANY_ADDRESS
ENV NEXT_PUBLIC_SOCIAL_LINKS=$NEXT_PUBLIC_SOCIAL_LINKS
ENV NEXT_PUBLIC_IMAGE_DOMAINS=$NEXT_PUBLIC_IMAGE_DOMAINS
ENV STRAPI_API_URL=$STRAPI_API_URL
ENV STRAPI_API_TOKEN=$STRAPI_API_TOKEN
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN npm run build

FROM node:22-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
COPY --from=builder /app ./
EXPOSE 3030
CMD ["npm", "run", "start", "--", "-p", "3030"]
